destroy:
	terraform destroy -auto-approve

format:
	terraform fmt

validate:
	terraform validate

show:
	terraform show

apply.container_name:
	terraform apply -var "container_name=OutroNome"

.PHONY: destroy